version: '3'
services:
  app:
    build: ./webapp
    volumes:
      - ./webapp/html:/usr/share/nginx/html
    ports:
      - "81:80"
  loadbal:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - app